### ISSUE TITLE
Prompt disappears on sourcing .zshrc using antigen

### ISSUE THREAD

**Issue by AGitBoy** [agkozak/agkozak-zsh-prompt#8] opened 2018-06-10 22:43 UTC
When using antigen, running this command
``` source ~/.zshrc ```

Causes the prompt to not show up. You can still type in commands, and other plugins work, but the prompt will not show up.

**Comment by agkozak** [comment] 2018-06-12 03:42
Thanks for reporting this problem. I cannot reproduce it, however. With a simple `.zshrc` that does nothing but source antigen and load my prompt, repeated sourcings only produce the expected message: "Seems agkozak/agkozak-zsh-theme is already installed!"

Would you be willing to share your `.zshrc`? I'll play with it and try to figure out what's happening. Thanks.

**Comment by AGitBoy** [comment] 2018-06-12 04:15
Ok. Here is my .zshrc:

```
######### Variables ##########
export SHELL=/usr/bin/zsh
# Various editor variables
export EDITOR=nvim
export VISUAL=nvim
# Neovim Pager
export PAGER=nvimpager

######### Aliases ##########
alias sl=ls 
alias page=$PAGER
alias edit=$EDITOR
alias c=clear
alias e=exit
alias open=xdg-open

######### Plugins ##########
source ~/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle vi-mode
antigen bundle pip
antigen bundle common-aliases
antigen bundle go
antigen bundle rust
antigen bundle ubuntu
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme agkozak/agkozak-zsh-theme 

antigen apply
```

If it is helpful, I'm on Kubuntu 18.04, with zsh version 5.4.2.

Other than this issue, I'm really loving this theme! It's good to find a theme that nearly perfectly fits my tastes and needs.

**Comment by agkozak** [comment] 2018-06-12 04:55
Try changing

    antigen theme agkozak/agkozak-zsh-theme

to

    antigen bundle agkozak/agkozak-zsh-theme

That works for me.

I'm going to look further into why `antigen theme` doesn't work properly with my prompt -- I think I can see what's going on, but I really don't use antigen much myself. [Doesn't this look like a similar problem?](https://github.com/zsh-users/antigen/issues/665)

**Comment by agkozak** [comment] 2018-06-12 14:56
It’s interesting to note that the author of the [pure](https://wwwapps.ups.com/tracking/tracking.cgi?tracknum=1ZEW96780224231321) prompt appear to have given up making `antigen theme` work with his prompt, and advises people to use `antigen bundle` instead. But I’ll look deeper.

**Comment by agkozak** [comment] 2018-06-12 16:38
[It looks as if](https://github.com/zsh-users/antigen/issues/652) something is broken in antigen v2.2.2 but has been fixed in the development version. Try running

    curl -L git.io/antigen-nightly > ~/antigen.zsh

and then see if typing

    zsh
    antigen theme agkozak/agkozak-zsh-theme

leaves you with a working prompt.

If you can confirm that that works, I'll update my documentation to encourage people to use `antigen bundle` just until antigen v2.2.3 is released. Thanks so much for your help, @AGitBoy!

**Comment by AGitBoy** [comment] 2018-06-12 20:03
It works now!  Thank you!

**Comment by agkozak** [comment] 2018-06-12 20:23
Thanks for helping me to improve my documentation!

**Comment by borekb** [comment] 2018-07-07 20:18
I had a similar problem and the only combination that worked for me was `antigen theme` and adding `autoload -Uz promptinit; promptinit` in my `.zshrc`. This is what I use now:

```
source "${funcsourcetrace[1]%/*}/antigen.zsh"
antigen use oh-my-zsh
antigen theme borekb/agkozak-zsh-theme@prompt-customization
antigen apply

autoload -Uz promptinit; promptinit
AGKOZAK_COLORS_BRANCH_STATUS=8
```

I'm not sure if promptinit should be required or not but without it, new shell sessions start without a customized prompt. Also, the combination of `antigen bundle` and `promptinit` leads only to the default prompt for me. I'm in MSYS2 on Windows, maybe it matters.

**Comment by agkozak** [comment] 2018-07-07 20:38
Thanks, @borekb -- I'll be happy to look into this.

Let me just confirm what you have tried so far.  Have you tried using simply

     antigen bundle agkozak/agkozak-zsh-theme

(not `antigen theme`), and if so, does that work?

Also, which version of antigen are you using?

**Comment by borekb** [comment] 2018-07-07 20:53
Yes, `antigen bundle`, both with and without `autoload -Uz promptinit; promptinit`, didn't work for me. I had to use `antigen theme` _and_ promptinit.

Oh, I'm still on Antigen 2.2.2, I assumed that they released a newer version since your earlier discussion in this issue but I was wrong. Will try again with the nightly build, sorry!

**Comment by borekb** [comment] 2018-07-07 21:04
With Antigen nightly, I couldn't get it working at all. Very strange is that even after switching back to 2.2.2, I couldn't get it working again. My `.zshrc` is as per the comment above, I can get the prompt working for the current shell if I manually invoke `antigen theme borekb/agkozak-zsh-theme@prompt-customization` again but as soon as I create a new session, I'm back to the default prompt. Which is strange because this was working just a couple of minutes ago.

The only safe way for me seems to be to source the theme directly from my `.zshrc`, which is ugly but works:

```
source "$HOME/.antigen/bundles/borekb/agkozak-zsh-theme-prompt-customization/agkozak-zsh-theme.plugin.zsh"
```

**Comment by agkozak** [comment] 2018-07-07 21:04
Thanks, yes, do try nightly and get back to me -- but either way, thanks for the new information about `antigen bundle` not always working -- I'll want to update the documentation again, at the very least.

**Comment by borekb** [comment] 2018-07-07 21:09
By the way, theoretically, if my `.zshrc` looked like this (which I assume should work):

```
source "${funcsourcetrace[1]%/*}/antigen.zsh"
antigen use oh-my-zsh
antigen bundle agkozak/agkozak-zsh-theme
antigen apply

autoload -Uz promptinit; promptinit
AGKOZAK_COLORS_BRANCH_STATUS=8
```

at which point should the code in `.antigen/bundles/agkozak/agkozak-zsh-theme/agkozak-zsh-theme.plugin.zsh` be executed? Is it at the `antigen apply` command? How does this command know it should invoke that specific file? Is that something about the `.plugin.zsh` extension? Sorry, beginner questions, I'm just thinking that maybe that `.zsh` file is not executed at all.

**Comment by agkozak** [comment] 2018-07-08 04:45
Help me to confirm that the following works. Try using this `.zshrc`:

    source "${funcsourcetrace[1]%/*}/antigen.zsh"
    antigen use oh-my-zsh
    antigen theme borekb/agkozak-zsh-theme@prompt-customization
    antigen apply

    AGKOZAK_COLORS_BRANCH_STATUS=8

(that is, leave out the line about `promptinit` -- I don't think it's necessary). Before restarting the shell, delete your `.antigen` directory.

When you start a new shell in MYS2, I think you'll find that the prompt isn't working. Now execute the following two commands

    antigen reset
    zsh

When the next shell launches, your custom prompt should be there, and it should continue to work until...well, that's where I don't have all the answers yet.

The problem seems to be with how antigen builds its cache. `antigen reset` rebuilds the cache -- that's why it should fix your problem, for a while at least. In answer to your earlier question, antigen's finding the `agkozak-zsh-theme.plugin.zsh` all right.

I actually don't use antigen myself, so it's very helpful to me that you're catching these problems! I'll try to have a fix for our problem soon.

**Comment by agkozak** [comment] 2018-07-08 05:23
I can see the cache (usually `~/.antigen/init.zsh`) not being build correctly the first time around. It seems only to happen on MSys2 and Cygwin, though. Sometimes there’s a path with two trailing slashes.

**Comment by agkozak** [comment] 2018-07-08 05:50
What's happening is that the `init.zsh` cache file has lines like

    #--- BUNDLES BEGIN


    #--- BUNDLES END

in it. When I reset the cache and restart `zsh`, they get filled out, thus:

    #--- BUNDLES BEGIN
    source '/home/agkoz/.antigen/bundles/agkozak/agkozak-zsh-theme/agkozak-zsh-theme.plugin.zsh';                                                                                                                   

    #--- BUNDLES END

So at first, nothing is getting sourced. I'll try to figure out what antigen doesn't like about my theme/bundle.

**Comment by borekb** [comment] 2018-07-08 07:04
Nice find, I can confirm that your `.zshrc` plus doing `antigen reset` manually fixes the problem.

**Comment by agkozak** [comment] 2018-07-08 21:50
I think there may be a problem with the way the antigen cache has worked in MSys2 and Cygwin starting in v2.2.0 -- even the common robbyrussell theme requires an `antigen reset` to display properly. I will gather my observations and show them to antigen's developer. In the meantime, you can go on using

    source /path/to/agkozak-zsh-theme.plugin.zsh

**Comment by sinetoami** [comment] 2018-09-01 07:01
@agkozak 
I'm sorry for reporting a comment now. But, a couples of days this issue appears on my environment. I tried install and apply the [Spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt) theme using the recommended approach on the [documentation](https://github.com/denysdovhan/spaceship-prompt#installing). Using `antigen bundle denysdovhan/spaceship-prompt spaceship`. I've omitted the url. So, my prompt disappeared. When I tried follow your advise, to use `antigen bundle` instead of `antigen theme`, my prompt stopped to disappears... but don't applies nothing about the theme. 

So what I did was install [this plugin](https://github.com/mafredri/zsh-async) before applying any theme. Works like a charm. Basically is what recommends the installation of the (Pure)[https://github.com/sindresorhus/pure#integration] theme.

I hope this helps. 

Thanks

**Comment by borekb** [comment] 2018-09-01 08:40
@sinetoami `zsh-async` doesn't work on Windows / MSYS2, it's actually one of the key strengths of this prompt that it implements asynchronicity in a way that works cross-platform. But your solution might help on non-Windows platforms, that's true.

**Comment by agkozak** [comment] 2018-09-01 14:59
@sinetoami I'm glad you found something that works for you!

**Closed by agkozak** 2018-09-01 14:59 UTC

**Comment by rob-eiq** [comment] 2022-03-26 00:36
Just wanted to chime in here, that for me, all that was needed was to run `zsh` after sourcing. 
I use an alias `sz="source ~/.zshrc && zsh"`
